/*  CRIACAO DE TABELA SEM CONSTRAINT  */
 
CREATE TABLE 
    ALUNO (
        MATRICULA NUMBER(10),
        NOME VARCHAR2(200),
        SEXO CHAR(1),
        DATA_NASC DATE
        );
        
/*  EXCLUSAO DE TABELA  */
DROP TABLE ALUNO CASCADE CONSTRAINTS;  

/* CRIACAO DE TABELA COM COSNTRAINT NOT NULL */

CREATE TABLE ALUNO (
    MATRICULA NUMBER(10) NOT NULL,
    NOME VARCHAR2(200) NOT NULL,
    SEXO CHAR(1),
    DATA_NASC DATE
    );

/* CRIACAO DE TABELA COM CONSTRAINT NOT NULL NOMEADA */

CREATE TABLE ALUNO (
    MATRICULA NUMBER(10) CONSTRAINT NN_ALUNO_MATRICULA NOT NULL,
    NOME VARCHAR2(200) CONSTRAINT NN_ALUNO_NOME NOT NULL,
    SEXO CHAR(1),
    DATA_NASC DATE
    );

/* CRIACAO DA TABELA MATERIA COM CONSTRAINT UNIQUE */

CREATE TABLE MATERIA (
    CODIGO NUMBER(4) NOT NULL,
    DESCRICAO VARCHAR2(200) UNIQUE
    );
    
/*  EXCLUSAO DE TABELA  */
DROP TABLE MATERIA CASCADE CONSTRAINTS; 

/* CRIACAO DE TABELA MATERIA COM CONSTRAINT NOMEADA - NIVEL COLUNA */

CREATE TABLE MATERIA (
    CODIGO NUMBER(4) CONSTRAINT NN_MATERIA_CODIGO NOT NULL,
    DESCRICAO VARCHAR2(200) CONSTRAINT UK_MATERIA_DESCRICAO UNIQUE
    );

/* CRIACAO DE TABELA MATERIA COM CONSTRAINT NOMEADA - NIVEL TABELA */
CREATE TABLE MATERIA (
    CODIGO NUMBER(4) CONSTRAINT NN_MATERIA_CODIGO NOT NULL,
    DESCRICAO VARCHAR2(200),
    CONSTRAINT UK_MATERIA_DESCRICAO UNIQUE(DESCRICAO)
    );
    
/* CRICAO DA TABELA MATERIA COM CONSTRAINT PRIMARY KEY */

CREATE TABLE MATERIA (
    CODIGO NUMBER(4) PRIMARY KEY,
    DESCRICAO VARCHAR2(200) UNIQUE
    );

/* CRIACAO DE TABELA MATERIA COM CONSTRAINT NOMEADA - NIVEL COLUNA */

CREATE TABLE MATERIA (
    CODIGO NUMBER(4) CONSTRAINT PK_MATERIA_CODIGO PRIMARY KEY,
    DESCRICAO VARCHAR2(200) CONSTRAINT UK_MATERIA_DESCRICAO UNIQUE
    );
    
 /* CRIACAO DE TABELA MATERIA COM CONSTRAIT NOMEADA  
 - NIVEL TABELA (PRIMARY KEY COMPOSTA) */
 
CREATE TABLE MATERIA (
    CODIGO NUMBER(4),
    SIGLA CHAR(2),
    DESCRICAO VARCHAR2(200) UNIQUE,
    
    CONSTRAINT PK_MATERIA_CODIGO_SIGLA PRIMARY KEY (CODIGO, SIGLA)
    );

/* CRIACAO DE TABELA ALUNO COM CONSTRAINT CHECK - NIVEL COLUNA */

CREATE TABLE ALUNO (
    MATRICULA NUMBER(4),
    NOME VARCHAR2(30),
    SEXO CHAR(1) CHECK (SEXO IN ('M', 'F', 'm', 'f'))
    );

/* CRIACAO DE TABELA ALUNO COM CONSTRAINT NOMEADA CHECK - NIVEL COLUNA*/

CREATE TABLE ALUNO (
    MATRICULA NUMBER(4),
    NOME VARCHAR2(30),
    SEXO CHAR(1) CONSTRAINT CK_ALUNO_SEXO CHECK (SEXO IN ('M', 'F'))
    );

/* CRIACAO DE TABELA ALUNO COM CONSTRAINT NOMEADA CHECK - NIVEL TABELA*/

CREATE TABLE ALUNO (
    MATRICULA NUMBER(4),
    NOME VARCHAR2(30),
    SEXO CHAR(1),
    
    CONSTRAINT CK_ALUNO_SEXO CHECK (SEXO IN ('M', 'F'))
    );
    
    



























    