-- Aula 06 - exemplos

/* EQUIJOIN
-- BUSCAR FUNCIONARIOS E SEUS RESPECTIVOS NOMES DE DEPARTAMENTO
*/

-- FORMA 1
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- FORMA 2
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- NON-EQUIJOIN
-- SELECIONAR SOBRENOME, SALARIO E GRADE DAS TABELA EMPLOYEES E JOB_GRADES
-- NOS QUAIS OS SALARIOS EESTEJAM ENTRE O MENOR E MAIOR SALARIO
SELECT * FROM JOB

SELECT E.LAST_NAME, E.SALARY, JG.GRADE_LEVEL
FROM EMPLOYEES E JOIN JOB_GRADES JG
ON E.SALARY BETWEEN JG.LOWEST_SAL  AND JG.HIGHEST_SAL;


/* 
TRAZER TODOS OS FUNCIONARIOS E RESPECTIVOS NOMES DE DEPARTAMENTOS
 */

-- INNER JOIN
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES e INNER JOIN DEPARTMENTS d
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID


-- LEFT JOIN
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES e LEFT JOIN DEPARTMENTS d
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
-- WHERE D.DEPARTMENT_ID IS NULL;

-- RIGHT JOIN
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES e RIGHT JOIN DEPARTMENTS d
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
--WHERE E.DEPARTMENT_ID IS NULL;

-- FULL JOIN
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES e FULL JOIN DEPARTMENTS d
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- SELF JOIN - TRAZER NOME E ID DO CARGO DE CADA FUNCIONARIO COM OS RESPECTIVOS IDS DE GERENTES E SEUS CARGOS
SELECT
	M.LAST_NAME AS MANAGER,
	M.JOB_ID AS MANAGER_JOB,
	W.LAST_NAME AS WORKER,
	W.JOB_ID AS WORKER_JOB
FROM
	EMPLOYEES W
JOIN EMPLOYEES M 
ON
	(M.EMPLOYEE_ID = W.MANAGER_ID)
ORDER BY
	M.DEPARTMENT_ID,
	M.JOB_ID;

-- CROSS JOIN
SELECT
E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES e CROSS JOIN DEPARTMENTS d;
