-- AULA 07 EXERCICIOS

-- 1
SELECT FIRST_NAME, upper(FIRST_NAME) AS UPPER FROM EMPLOYEES;

-- 2
SELECT
	FIRST_NAME,
	HIRE_DATE,
	EXTRACT(YEAR FROM sysdate) - EXTRACT(YEAR FROM hire_date) || ' ' || 'years' AS WORKING_TIME
FROM
	EMPLOYEES;

-- 3
SELECT * FROM EMPLOYEES WHERE SUBSTR(FIRST_NAME, 1, 1) = 'M';
SELECT COUNT (*) FROM EMPLOYEES WHERE SUBSTR(FIRST_NAME, 1, 1) = 'M';

-- 4
SELECT FIRST_NAME, SALARY, ceil(SALARY) AS ROUND_SALARY
FROM EMPLOYEES;