-- EXERCICIO INSERT 

-- EXCLUI AS TABELAS CASO EXISTAM
DROP TABLE CIENTISTA CASCADE CONSTRAINTS PURGE;
DROP TABLE CLIENTE CASCADE CONSTRAINTS PURGE;

-- CRIA A TABELA CIENTISTA
-- EX 1
CREATE TABLE CIENTISTA (
	CODIGO NUMBER(4) CONSTRAINT PK_CIENTISTA_CODIGO PRIMARY KEY,
	NOME VARCHAR2(50) CONSTRAINT NN_CIENTISTA_NOME NOT NULL,
	DT_NASC DATE,
	SEXO CHAR(1) CONSTRAINT CK_CIENTISTA_SEXO CHECK (SEXO IN ('F', 'M'))
);

INSERT INTO CIENTISTA VALUES (1010, 'STEPHEN KING', '08/01/1942', 'M');
INSERT INTO CIENTISTA VALUES (1011, 'ALBERT EINSTEIN', '14/03/1879', 'M');
INSERT INTO CIENTISTA VALUES (1012, 'ISAAC NEWTON', '04/01/1643', 'M');
INSERT INTO CIENTISTA VALUES (1013, 'GALILEU GALILEI', '15/02/1564', 'M', '08/01/1642');
INSERT INTO CIENTISTA VALUES (1014, 'NICOLAU COPERNICO', '19/02/1473', 'M', '24/05/1543');

COMMIT;



-- DESAFIO - INSERT 
-- EX 2
CREATE TABLE CLIENTE (
	CODIGO NUMBER(4) CONSTRAINT PK_CLIENTE_CODIGO PRIMARY KEY,
	NOME VARCHAR(50) CONSTRAINT NN_CLIENTE_NOME NOT NULL
);

INSERT INTO CLIENTE SELECT CODIGO, NOME FROM CIENTISTA;
COMMIT;

SELECT * FROM CLIENTE;

-- EX 3
ALTER TABLE CIENTISTA ADD DT_OBTO DATE;

UPDATE CIENTISTA SET DT_OBTO = '14/03/2018' WHERE CODIGO = 1010;
UPDATE CIENTISTA SET DT_OBTO = '18/04/1955' WHERE CODIGO = 1011;
UPDATE CIENTISTA SET DT_OBTO = '31/03/1727' WHERE CODIGO = 1012;
UPDATE CIENTISTA SET DT_OBTO = '08/01/1642' WHERE CODIGO = 1013;
UPDATE CIENTISTA SET DT_OBTO = '24/05/1543' WHERE CODIGO = 1014;
COMMIT;

UPDATE CIENTISTA SET NOME = 'EINSTEIN' WHERE CODIGO = 1011;
UPDATE CIENTISTA SET NOME = 'NEWTON' WHERE CODIGO = 1012;


--DESAFIO UPDATE
-- EX 1

ALTER TABLE CLIENTE ADD DT_NASC DATE;

SELECT * FROM CLIENTE;
SELECT * FROM CIENTISTA;

UPDATE CLIENTE CL
    SET CL.DT_NASC = (
        SELECT CI.DT_NASc
        FROM CIENTISTA CI
        WHERE CI.CODIGO = CL.CODIGO
        );

       
--DELETE
--EX 1       
DELETE FROM CIENTISTA
WHERE TO_CHAR(DT_NASC, 'MM') = '02';

--EX 1  - SOLUCAO 2
DELETE FROM CIENTISTA
WHERE EXTRACT (MONTH FROM dt_nasc) = '02';

--EX 1  - SOLUCAO 3 - NAO RECOMENDADO POIS DIAS QUE SE INICIAM COM 02 E ANO QUE TERMINEM COM 02 TAMBÉM SERÃO EXCLUÍDOS
DELETE FROM CIENTISTA
WHERE DT_NASC LIKE '%02%';

-- DESAFIO
DELETE FROM CLIENTE WHERE CODIGO NOT IN (SELECT CODIGO FROM CIENTISTA);