-- EXERCICIOS - AULA 6
/* TRAZER TODOS OS FUNCIONARIOS LISTANDO CÓDIGO, NOME E DATA DE CONTRATAÇÃO
E NOME DE DEPARTAMENTO. FILTRAR APENAS FUNCIONARIOS DO DEPARTAMENTO 90
*/
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.HIRE_DATE, D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
AND D.DEPARTMENT_ID = 90
ORDER BY E.EMPLOYEE_ID;

/*
 * 01 - SELECIONANDO TODOS OS FUNCIONARIOS, OS QUAIS O DEPARTMENT_ID
 * 10 E 30, ORDENANDO POR NOME DE DEPARTAMENTO
 * */

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID BETWEEN 10 AND 30
ORDER BY D.DEPARTMENT_NAME;

/* 02 - Selecionando todos os funcionários, EXCETO OS FUNCIONARIOS
DOS DEPARTAMENTOS ENTRE 50 E 100*/
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID NOT BETWEEN 50 AND 100
ORDER BY 1;

/* 03 - Selecionar id, nome, sobrenome e salario de funcionarios
que possuam salario maior ou igual a 3000 e que contenham a letra 'a' e/ou 'A'
no primeiro nome*/
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM EMPLOYEES E
WHERE E.SALARY >= 3000
AND upper(E.FIRST_NAME) LIKE UPPER('%a%')
ORDER BY E.SALARY;

/* 04 - Selecionar todos os nomes de funcionarios que tenham
sido promovidos em algum momento*/
SELECT * FROM JOBS WHERE JOB_ID = 'IT_PROG';
SELECT JOB_ID, SALARY  FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG';


SELECT DISTINCT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.JOB_ID, E.SALARY
FROM EMPLOYEES E
INNER JOIN JOB_HISTORY JH
ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
ORDER BY E.SALARY;
