-- AULA 5 - EXEMPLOS

-- REMOVE AS TABELAS
DROP TABLE PRODUTO CASCADE CONSTRAINTS PURGE;
DROP TABLE CIENTISTA CASCADE CONSTRAINTS PURGE;

-- CRIACAO DE TABELAS E INSERSAO DE LINHAS
CREATE TABLE PRODUTO
(CODIGO    INTEGER     PRIMARY KEY,
DESCRICAO VARCHAR(50) NOT NULL,
VALOR     NUMBER(6,2) NOT NULL);

INSERT INTO PRODUTO
VALUES (100,'CAMISETA',80.00);

INSERT INTO PRODUTO
VALUES (101,'POLO',120.00);

INSERT INTO PRODUTO
VALUES (102,'CAMISA',150.00);

INSERT INTO PRODUTO
VALUES (103,'CALÃ‡A',100.00);

INSERT INTO PRODUTO
VALUES (104,'SHORTS',70.00);

COMMIT;

CREATE TABLE CIENTISTA
(CODIGO  INT         PRIMARY KEY,
NOME    VARCHAR(50) NOT NULL,
DT_NASC DATE,
SEXO    CHAR(1) );

 
INSERT INTO CIENTISTA 
VALUES (1010,'STEPHEN HAWKING','08/01/1942','M');

INSERT INTO CIENTISTA 
VALUES (1011,'ALBERT EINSTEIN','14/03/1879','M');

INSERT INTO CIENTISTA 
VALUES (1012,'ISAAC NEWTON','04/01/1643','M');

INSERT INTO CIENTISTA 
VALUES (1013,'GALILEU GALILEI','15/02/1564','M');

INSERT INTO CIENTISTA 
VALUES (1014,'NICOLAU COPERNICO','19/02/1473','M');
COMMIT;


-- SELECT SIMPLES - PROJECAO
SELECT * FROM PRODUTO;
SELECT * FROM CIENTISTA;

SELECT descricao, valor FROM PRODUTO;
SELECT descricao, (valor + 10) * 1.05 FROM PRODUTO;
SELECT descricao, (valor + 10) * 1.05 AS vlr_calculado FROM PRODUTO;
SELECT descricao, valor, (valor + 10) * 1.05 AS vlr_calculado FROM produto;

-- selecao com condicional
SELECT * FROM produto WHERE valor > 100;

-- selecao ordenada
SELECT * FROM produto ORDER BY valor;

-- selecao ordenada decrescente
SELECT * FROM produto ORDER BY valor DESC;

-- select com posicao
SELECT * FROM produto ORDER BY 1, 2, 3;

-- traz um range de valores
SELECT * FROM PRODUTO WHERE valor BETWEEN 80 AND 120;

-- utilizando like
SELECT * FROM cientista WHERE nome LIKE 'S%';
SELECT * FROM cientista WHERE nome LIKE '%AA%';
SELECT * FROM cientista WHERE nome LIKE '%O';

SELECT * FROM cientista WHERE nome LIKE '_T%';
SELECT * FROM cientista WHERE nome LIKE '__A%';
SELECT * FROM cientista WHERE nome LIKE 'N_C%';

-- operadores lógicos: AND, OR e NOT 
-- AND
SELECT * FROM PRODUTO WHERE valor > 100 AND DESCRICAO LIKE 'CA%';

-- OR
SELECT * FROM PRODUTO WHERE valor > 100 OR DESCRICAO LIKE 'CA%';

-- NOT
SELECT * FROM PRODUTO WHERE NOT valor > 80;



















