-- AULA 4 - DML
-- COMMIT E ROLLBACK
DROP TABLE MATERIA CASCADE CONSTRAINTS;

CREATE TABLE MATERIA (
	COD_MATERIA NUMBER,
	DESCRICAO VARCHAR2(20)
);

INSERT INTO MATERIA VALUES (1, 'BANCO DE DADOS');
INSERT INTO MATERIA VALUES (2, 'BI');

SELECT * FROM MATERIA;

COMMIT;

INSERT INTO MATERIA VALUES (3, 'BIG DATA');

ROLLBACK;

-- INSERT
SELECT * FROM CATEGORIA;

ALTER TABLE CATEGORIA DROP CONSTRAINT CK_CATEGORIA;

INSERT INTO CATEGORIA VALUES (3, 'FRUTA');

COMMIT;

-- INSERIR VARIAS LINHA DE UMA VEZ
INSERT ALL
INTO CATEGORIA VALUES (5, 'LEGUME')
INTO CATEGORIA VALUES (6, 'CARNE')
INTO CATEGORIA VALUES (7, 'GRAOS')
INTO CATEGORIA VALUES (8, 'MERCEARIA')
SELECT * FROM DUAL;

COMMIT;

-- A TABELA DUAL
SELECT SYSDATE FROM DUAL;
SELECT USER FROM DUAL;
SELECT SEQ_CATEGORIA.NEXTVAL FROM DUAL;
SELECT SEQ_CATEGORIA.CURRVAL FROM DUAL;

--INSERÇÃO COM VALORES NULOS

-- FORMA 1 - EXPLICITO
INSERT INTO CATEGORIA VALUES (20, NULL);

-- FORMA 2 - IMPLICITO
INSERT INTO CATEGORIA (COD_CATEGORIA) VALUES (21);

COMMIT;

-- UPDATE
DROP TABLE PRODUTO CASCADE CONSTRAINTS;

CREATE TABLE PRODUTO (
	CODIGO INT CONSTRAINT PK_PRODUTO_CODIGO PRIMARY KEY,
	DESCRICAO VARCHAR2(50),
	VALOR NUMBER (8,2)
);

INSERT INTO PRODUTO VALUES (1010,'CAMISA',80.00);
INSERT INTO PRODUTO VALUES (1011,'POLO',120.00);
INSERT INTO PRODUTO VALUES (1012,'CAMISA',150.00);
INSERT INTO PRODUTO VALUES (1013,'CAMISA',100.00);
INSERT INTO PRODUTO VALUES (1014,'SHORTS',70.00);

COMMIT;

UPDATE PRODUTO SET DESCRICAO = 'CAMISETA' WHERE CODIGO = 1010;

COMMIT;

SELECT * FROM PRODUTO;

UPDATE PRODUTO SET VALOR = VALOR * 1.10;

UPDATE PRODUTO SET DESCRICAO = 'CALCA JEANS', VALOR = 150 WHERE CODIGO = 1013;

-- DELETE 
-- 1 LINHA
DELETE FROM PRODUTO WHERE CODIGO = 1013;
COMMIT;

-- LINHAS QUE ATENDEM A CONDICAO DO WHERE
DELETE FROM PRODUTO WHERE VALOR <= 100;
COMMIT;

-- ALTER DRP CREATE TAVLE E ETC TEM COMMITS IMPLICITOS

-- ALTERANDO FORMATACAO DE DATA - APENAS NA SESSAO
ALTER SESSION  SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

-- ALTERANDO IDIOMA - APENAS NA SESSAO
ALTER SESSION SET NLS_DATE_LANGUAGE = 'PORTUGUESE';

SELECT SYSDATE, TO_CHAR(SYSDATE, 'MON') MESABV, TO_CHAR(SYSDATE, 'MONTH') MES FROM DUAL;

-- TABELAS DE DESCRICAO
-- MOSTRA TODOS OS OBJETOS PERTENCENTES AO USUARIO
SELECT * FROM USER_OBJECTS;

-- MOSTRA TODAS AS COLUNAS DAS TABELAS PERTENCENTES AO USUARIO
SELECT * FROM USER_TAB_COLUMNS;