-- AULA 2 - EXERCICIOS

--EXCLUI AS TABELAS
drop table item_produto CASCADE CONSTRAINTS;
drop table produto CASCADE CONSTRAINTS;
drop table categoria CASCADE CONSTRAINTS;
drop table materia_prima CASCADE CONSTRAINTS;

-- CRIA A TABELA CATEGORIA
CREATE TABLE CATEGORIA (
    COD_CATEGORIA INT CONSTRAINT PK_CATEGORIA_COD_CATEGORIA PRIMARY KEY,
    CATEGORIA VARCHAR2(255) CONSTRAINT UK_CATEGORIA UNIQUE,
                            CONSTRAINT CK_CATEGORIA CHECK 
                            (CATEGORIA IN ('DOCE', 'BEBIDA', 'CONGELADO'))
                        );

--CRIA A TABELA MATERIA PRIMA
CREATE TABLE MATERIA_PRIMA (
    COD_MATERIA_PRIMA INT CONSTRAINT PK_MATERIA_PRIMA PRIMARY KEY,
    MATERIA_PRIMA VARCHAR2(255) CONSTRAINT UK_MATERIA_PRIMA UNIQUE
    );

-- CRIA A TABELA PRODUTO
-- SOLU플O CONSTRAINT NIVEL COLUNA
CREATE TABLE PRODUTO (
    COD_PRODUTO INT CONSTRAINT PK_PRODUTO PRIMARY KEY,
    COD_CATEGORIA INT CONSTRAINT NN_PRODUTO_COD_CAT NOT NULL
                      CONSTRAINT FK_PRODUTO_COD_CAT REFERENCES CATEGORIA (COD_CATEGORIA),
    PRODUTO VARCHAR2(255) CONSTRAINT UK_PRODUTO UNIQUE
    );
        
-- SOLU플O CONSTRAINT NIVEL TABELA
CREATE TABLE PRODUTO (
    COD_PRODUTO INT CONSTRAINT PK_PRODUTO PRIMARY KEY,
    COD_CATEGORIA INT CONSTRAINT NN_PRODUTO_COD_CAT NOT NULL,
    PRODUTO VARCHAR2(255),
    
    CONSTRAINT FK_PRODUTO_COD_CAT FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA,
    CONSTRAINT UK_PRODUTO UNIQUE (PRODUTO)
    );

-- CRIA A TABELA ITEM_PRODUTO
-- SOLU플O CONSTRAINT NIVEL COLUNA
CREATE TABLE ITEM_PRODUTO (
    COD_PRODUTO INT CONSTRAINT FK_ITEM_PRODUTO_PRODUTO REFERENCES PRODUTO,
    COD_MATERIA_PRIMA INT CONSTRAINT FK_ITEM_PRODUTO_MATERIA_PRIMA REFERENCES MATERIA_PRIMA,
    QUANTIDADE INT CONSTRAINT NN_ITEM_PRODUTO_QTD NOT NULL,
    
    CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (COD_PRODUTO, COD_MATERIA_PRIMA)
    );

-- EXCLUI A TABELA ITEM_PRODUTO
DROP TABLE ITEM_PRODUTO CASCADE CONSTRAINTS;

--SOLU플O CONSTRAINT NIVEL TABELA
CREATE TABLE ITEM_PRODUTO (
    COD_PRODUTO  INT,
    COD_MATERIA_PRIMA INT,
    QUANTIDADE INT CONSTRAINT NN_ITEM_PRODUTO_QTD NOT NULL,
    
    CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (COD_PRODUTO, COD_MATERIA_PRIMA),
    CONSTRAINT FK_ITEM_PRODUTO_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO,
    CONSTRAINT FK_ITEM_PRODUTO_MATERIA_PRIMA FOREIGN KEY (COD_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA
    );
    






